sudo: required

language: python

services:
  - docker

script:
  - docker build -t lab41/base_notebook 01_base_notebook

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag lab41/base_notebook pcallier/base_notebook;
      docker push pcallier/base_notebook;
    fi
