sudo: required

language: generic

services:
  - docker

script:
  - docker build -t lab41/base-notebook 01_base_notebook
  - docker build -t lab41/tensorflow-notebook 02_deep_learning

after_success:
  - echo "TRAVIS_BRANCH\: $TRAVIS_BRANCH";
    echo "TRAVIS_REPO_SLUG\: $TRAVIS_REPO_SLUG"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_REPO_SLUG" == "Lab41/nbserver" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
      docker push lab41/base-notebook &&
      docker push lab41/tensorflow-notebook;
    fi
